app:
  title: Ticketera
  width: 880
  height: 640
  options: 10
  color:
    base: [0.48, 0.576, 0.624, 1]
    text: [1, 1, 1, 1]
    qrBackground: [1, 1, 1, 0.01]
options:
  option_a:
    name: "Send"
    code: "S"
  option_b:
    name: "Receipt"
    code: "R"
  option_c:
    name: "Info"
    code: "I"
  option_d:
    name: "Test D"
    code: "D"
  option_e:
    name: "Test E"
    code: "E"
  option_f:
    name: "Test F"
    code: "F"
  option_g:
    name: "Test G"
    code: "G"
  option_h:
    name: "Test H"
    code: "H"
  option_i:
    name: "Test I"
    code: "I"
  option_j:
    name: "Test J"
    code: "J"
