app:
  title: Ticketera
  width: 880
  height: 440
  options: 3
  color:
    base: [0.48, 0.576, 0.624, 1]
    text: [1, 1, 1, 1]
    qrBackground: [1, 1, 1, 0.01]
options:
  option_a:
    name: "Send"
    code: "S"
  option_b:
    name: "Receipt"
    code: "R"
  option_c:
    name: "Info"
    code: "I"
  option_d:
    name:
    code:
  option_e:
    name:
    code:
  option_f:
    name:
    code: