app:
  title: Ticketera
  width: 880
  height: 440
  options: 2
options:
  option_a:
    name: "Send"
    code: "S"
  option_b:
    name: "Receipt"
    code: "R"
  option_c:
    name: "Info"
    code: "I"
  option_d:
    name:
    code:
  option_e:
    name:
    code:
  option_f:
    name:
    code: